/* Generated by scripts/embed_vga_image.py from gaysans.txt — do not edit. */
#ifndef GAYSANS_RGB_H
#define GAYSANS_RGB_H

#include <stdint.h>

#define VGA_IMAGE_RGB_BYTES 28800u

extern const uint8_t gaysans_rgb[VGA_IMAGE_RGB_BYTES];

#define VGA_IMAGE_ARRAY gaysans_rgb

#endif
