/* Generated by scripts/embed_vga_image.py from plankton.bmp — do not edit. */
#ifndef VGA_IMAGE_RGB_H
#define VGA_IMAGE_RGB_H

#include <stdint.h>

#define VGA_IMAGE_RGB_BYTES 28800u

extern const uint8_t vga_image_rgb[VGA_IMAGE_RGB_BYTES];

#define VGA_IMAGE_ARRAY vga_image_rgb

#endif
